### ISSUE TITLE
all meshes are importing at world origin

### ISSUE THREAD

**Issue by imgrantye** [kree-nickm/ninjaripper-blender-import#7]
first off - thank you for your hardwork for this dope ass tool! my only issue i've faced so far is when importing the entire folder, the meshes no longer retain their original location. is this a fixable problem or is it meant to be this way?

**Comment by kree-nickm** [comment]
That's just how NinjaRipper works. It treats every single model as its own separate thing, and doesn't store anything about where they are in relation to each other in the scene. So there's not really anything that can be fixed.
